In [1]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [2]:
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica

In [3]:
svm_clf = Pipeline([
 ("scaler", StandardScaler()),
 ("linear_svc", LinearSVC(C=1, loss="hinge")),
 ])

In [4]:
svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [5]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [6]:
#Versicolor

X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 1).astype(np.float64) # Iris-Versicolor

In [7]:
svm_clf = Pipeline([
 ("scaler", StandardScaler()),
 ("linear_svc", LinearSVC(C=1, loss="hinge")),
 ])

In [8]:
svm_clf.fit(X, y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [9]:
svm_clf.predict([[5.5, 1.7]])

array([0.])

In [10]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## Non linear svm

In [11]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [12]:
make_moons()

(array([[ 9.49055747e-01,  3.15108218e-01],
        [ 1.22252093e+00, -4.74927912e-01],
        [ 1.03205158e+00, -4.99486216e-01],
        [ 9.26916757e-01,  3.75267005e-01],
        [ 2.05460725e-03,  4.35929780e-01],
        [ 1.40478334e+00, -4.14412623e-01],
        [ 7.30832427e-02,  1.24732995e-01],
        [ 1.92691676e+00,  1.24732995e-01],
        [-6.23489802e-01,  7.81831482e-01],
        [ 9.00968868e-01,  4.33883739e-01],
        [-5.72116660e-01,  8.20172255e-01],
        [ 6.72300890e-01,  7.40277997e-01],
        [ 8.40400105e-01, -4.87181783e-01],
        [ 1.94905575e+00,  1.84891782e-01],
        [ 1.00000000e+00,  0.00000000e+00],
        [ 1.61911895e-01, -4.55349012e-02],
        [-9.81559157e-01,  1.91158629e-01],
        [ 9.97945393e-01,  6.40702200e-02],
        [ 1.09602303e+00, -4.95379113e-01],
        [-9.67294863e-01,  2.53654584e-01],
        [ 2.38554042e-01, -1.48228395e-01],
        [-6.72300890e-01,  7.40277997e-01],
        [ 9.81559157e-01,  1.911

In [13]:
X, y = make_moons(n_samples=200, noise=0.2, random_state=42)

In [14]:
X.shape

(200, 2)

In [15]:
y.shape

(200,)

In [16]:
polynomial_svm_clf = Pipeline([
 ("poly_features", PolynomialFeatures(degree=3)),
 ("scaler", StandardScaler()),
 ("svm_clf", LinearSVC(C=10, loss="hinge"))
 ])

In [17]:
polynomial_svm_clf.fit(X, y)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge'))])

In [18]:
polynomial_svm_clf.predict([[1.2,3]])

array([1], dtype=int64)

## Polynomial Kernel

In [19]:
from sklearn.svm import SVC

poly_kernel_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5))
    ])
poly_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

In [20]:
poly_kernel_svm_clf.predict([[1.2,3]])

array([0], dtype=int64)

## SVM Regression

#### Linear

In [21]:
from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=1.5)

In [22]:
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica

In [23]:
svm_reg.fit(X, y)

LinearSVR(epsilon=1.5)

In [24]:
svm_reg.predict([[5.5, 1.7]])

array([0.])

#### Non linear

In [25]:
from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X, y)

SVR(C=100, degree=2, kernel='poly')

## Decision Tree

In [26]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
X = iris.data[:, 2:] # petal length and width
y = iris.target
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [32]:
pip install graphviz

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/47.1 kB ? eta -:--:--
   ---------------------------------------- 47.1/47.1 kB 784.8 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [33]:
from sklearn.tree import export_graphviz
import graphviz
viz = export_graphviz(
 tree_clf,
 feature_names=iris.feature_names[2:],
 class_names=iris.target_names,
 rounded=True,
 filled=True
 )

graphviz.Source(viz)

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH